cơ sở dữ liệu của Brand

select * from Brands
insert into Brands(BrandName,Image,Url,Description)
values
(N'Highland Coffee','highlandcoffee.jpg','https://www.highlandscoffee.com.vn/',N'Ẩm thực & Giải khát'),
(N'Starbucks Coffee','starbuckscoffee.jpg','https://www.starbucks.vn/',N'Ẩm thực & Giải khát'),
(N'Haidilao','haidilao.jpg','https://www.haidilao-inc.com/us',N'Ẩm thực & Giải khát'),
(N'Sumo BBQ','sumobbq.jpg','https://sumo-bbq.com/',N'Ẩm thực & Giải khát'),
(N'GoGi House','gogihouse.jpg','https://gogi.com.vn/',N'Ẩm thực & Giải khát'),
(N'Kichi Kichi','kichikichi.jpg','https://kichi.com.vn/',N'Ẩm thực & Giải khát'),
(N'Hutong','hutong.jpg','https://hutong.com.vn/',N'Ẩm thực & Giải khát'),
(N'Khao Lao','khaolao.jpg','https://khaolao.vn/',N'Ẩm thực & Giải khát'),
(N'Thai Express','thaiexpress.jpg','https://thaiexpress.com.vn/',N'Ẩm thực & Giải khát'),
(N'Buffet Hoàng Yến','buffethoangyen.jpg','https://hoangyenbuffet.com/',N'Ẩm thực & Giải khát'),
(N'Texas Chicken','texaschicken.jpg','https://texaschicken.com/',N'Ẩm thực & Giải khát'),
(N'V.HAIYEN','v.haiyen.jpg','https://vhaiyen.vn/',N'Ẩm thực & Giải khát'),
(N'Dookki','dookki.jpg','https://www.dookkimalaysia.com/',N'Ẩm thực & Giải khát'),
(N'Pizza company','pizzacompany.jpg','https://thepizzacompany.vn/',N'Ẩm thực & Giải khát'),
(N'MARUKAME UDON','marukameudon.jpg','https://lotusdelivery.vn/',N'Ẩm thực & Giải khát'),
(N'BEE CHENG HIANG','beechenghiang.jpg','https://www.beechenghiang.com.sg/',N'Ẩm thực & Giải khát'),
(N'AKA House','akahouse.jpg','https://akahouse.com.vn/',N'Ẩm thực & Giải khát'),
(N'Buffet Lẩu Nướng 88','88.jpg','https://monviet88.com/',N'Ẩm thực & Giải khát'),
(N'Al Fresco’s','alfresco.jpg','https://alfrescos.com.vn/',N'Ẩm thực & Giải khát'),
(N'Tasaki BBQ','tasakibbq.jpg','https://tasaki.vn/',N'Ẩm thực & Giải khát'),
(N'Hotpot story','hotpotstory.jpg','https://hotpotstory.vn/',N'Ẩm thực & Giải khát'),
(N'CHANG KANG KUNG','CHANGKANGKUNG.jpg','https://newpearl.com.vn/',N'Ẩm thực & Giải khát'),
(N'MEI WEI','MEIWEI.jpg','https://meiwei.vn/',N'Ẩm thực & Giải khát'),
(N'KING BBQ','KINGBBQ.jpg','https://kingbbq.vn/',N'Ẩm thực & Giải khát'),
(N'Buffet Lẩu LokLok','LokLok.jpg','http://kikihotpot.com/en/home-page/',N'Ẩm thực & Giải khát'),
(N'YAMAZAKI BAKERY','YAMAZAKIBAKERY.jpg','https://www.facebook.com/vietnamyamazaki/?locale=vi_VN',N'Ẩm thực & Giải khát'),
(N'BOBAPOP','BOBAPOP.jpg','https://bobapop.com.vn/',N'Ẩm thực & Giải khát'),
(N'Shabu Ya','shabuya.jpg','https://shabuya.com.vn/trang-chu/',N'Ẩm thực & Giải khát'),
(N'Mak Mak','makmak.jpg','https://www.facebook.com/makmak.thaikitchen?mibextid=dGKdO6',N'Ẩm thực & Giải khát'),
(N'Jollibee','jollibee.jpg','https://jollibee.com.vn/',N'Ẩm thực & Giải khát'),
(N'Lotteria','lotteria.jpg','https://www.lotteria.vn/',N'Ẩm thực & Giải khát'),
(N'Phúc Long','phuclong.jpg','https://www.phuclong.com.vn/',N'Ẩm thực & Giải khát'),
(N'Spicy Box','spicybox.jpg','https://www.facebook.com/spicyboxvn/?locale=vi_VN',N'Ẩm thực & Giải khát'),
(N'Toco Toco','tocotoco.jpg','https://tocotocotea.com/',N'Ẩm thực & Giải khát'); 
(N'UNIQLO','UNIQLO.jpg','https://www.uniqlo.com/vn/vi/',N'Thời trang & Phụ kiện'),
(N'Levi’s','levi.jpg','https://levi.com.vn/',N'Thời trang & Phụ kiện'),
(N'ALDO','aldo.jpg','https://aldoshoes.vn/',N'Thời trang & Phụ kiện'),
(N'Charles & Keith','c&k.jpg','https://www.charleskeith.com/sg',N'Thời trang & Phụ kiện'),
(N'Nike','nike.jpg','https://www.nike.com/vn/',N'Thời trang & Phụ kiện'),
(N'Ecco','ecco.jpg','https://eccovietnam.vn/',N'Thời trang & Phụ kiện'),
(N'Pedro','pedro.jpg','https://www.pedroshoes.com/catalog/home',N'Thời trang & Phụ kiện'),
(N'MUJOSH','mujosh.jpg','https://www.maisononline.vn/?view=women',N'Thời trang & Phụ kiện'),
(N'Adidas','adidas.jpg','https://www.adidas.com.vn/vi',N'Thời trang & Phụ kiện'),
(N'SUNNIES STUDIOS','sunnies.jpg','https://www.acfc.com.vn/sunnies-studios.html?utm_source=Google&utm_medium=Shopping-ECOM&utm_campaign=ACFC&utm_content=ACFC&gclid=CjwKCAjwkNOpBhBEEiwAb3MvvayREoBIVhFLwnWeoB7gNijHJOiv4z-ihqABF9OAm20dwIGELfGYTxoCiJkQAvD_BwE',N'Thời trang & Phụ kiện'),
(N'PARFOIS','aldo.jpg','https://www.acfc.com.vn/parfois.html?fbclid=IwY2xjawF7EBVleHRuA2FlbQIxMAABHSTxWJGJZGREvsv54IckMeYsifV-0ButQ3bt15_JJg23Hy1c8yneRp7Byw_aem_MOk2BUmtXUz99g_K4txC2w',N'Thời trang & Phụ kiện'),
(N'ĐÔNG HẢI','donghai.jpg','https://shopdonghai.com/',N'Thời trang & Phụ kiện'),
(N'VASCARA','vascara.jpg','https://www.vascara.com/',N'Thời trang & Phụ kiện'),
(N'Lộc Phúc','locphuc.jpg','https://locphuc.com.vn/',N'Thời trang & Phụ kiện'),
(N'PNJ','pnj.jpg','https://www.pnj.com.vn/',N'Thời trang & Phụ kiện'),
(N'SkyWatch','skywatch.jpg','https://skywatch.vn/',N'Thời trang & Phụ kiện'),
(N'Tân Tân Watch','tantan.jpg','https://donghotantan.vn/',N'Thời trang & Phụ kiện'),
(N'Casio','casio.jpg','https://www.casio.com/vn/',N'Thời trang & Phụ kiện'),
(N'TITAN','titan.jpg','https://www.titanwatches.vn/',N'Thời trang & Phụ kiện'),
(N'Skechers','skechers.jpg','https://www.skechers.com/',N'Thời trang & Phụ kiện'),
(N'MLB','mlb.jpg','https://www.maisononline.vn/collections/mlb',N'Thời trang & Phụ kiện'),
(N'Crocs','cros.jpg','https://www.crocs.com.vn/',N'Thời trang & Phụ kiện'),
(N'PUMA','puma.jpg','https://www.maisononline.vn/collections/puma',N'Thời trang & Phụ kiện'),
(N'Matsumoto Kiyoshi','matsukiyo.jpg','https://www.matsukiyo.vn/',N'Thời trang & Phụ kiện'),
(N'COLOR BOX','colorbox.jpg','https://colorbox.vn/',N'Thời trang & Phụ kiện'),
(N'PUCINI','pucini.jpg','https://www.pucini.vn/',N'Thời trang & Phụ kiện'),
(N'GIORDANO','giordano.jpg','https://www.giordano.com/vn',N'Thời trang & Phụ kiện'),
(N'GUMAC','gumac.jpg','https://gumac.vn/',N'Thời trang & Phụ kiện'),
(N'Rechic','rechic.jpg','https://rechic.vn/',N'Thời trang & Phụ kiện'),
(N'MARC','marc.jpg','https://marc.com.vn/',N'Thời trang & Phụ kiện'),
(N'HAPPY ZOO','happyzoo.jpg','https://www.facebook.com/HappyZooStore/?locale=vi_VN',N'Thời trang & Phụ kiện'),
(N'JOVEN','joven.jpg','https://joven.vn/',N'Thời trang & Phụ kiện'),
(N'Bon Bon','bonbon.jpg','https://bonbonunderwear.com.vn/',N'Thời trang & Phụ kiện'),
(N'VERA','vera.jpg','https://vera.com.vn/',N'Thời trang & Phụ kiện'),
(N'RABITY','rabity.jpg','https://rabity.vn/',N'Thời trang & Phụ kiện'),
(N'BOO BÒ SỮA','boo.jpg','https://boo.vn/',N'Thời trang & Phụ kiện'),
(N'NINOMAXX','nino.jpg','https://ninomaxxconcept.com/',N'Thời trang & Phụ kiện'),
(N'SMIGGLE','smiggie.jpg','https://www.facebook.com/smiggleVN.official/',N'Thời trang & Phụ kiện'),
(N'BAA BABY','baa.jpg','https://baababy.com.vn/',N'Thời trang & Phụ kiện'),
(N'JOHN HENRY','john.jpg','https://johnhenry.vn/',N'Thời trang & Phụ kiện');
(N'Phương Nam Book City','phuongnam.jpg','https://www.pnc.com.vn/vi',N'Học tập & Giải Trí'),
(N'CLEVER BOX','clever.jpg','https://cleverbox.vn/',N'Học tập & Giải Trí'),
(N'ILA','ila.jpg','https://ila.edu.vn/',N'Học tập & Giải Trí'),
(N'BIGFUN PLAYGROUND','bigfun.jpg','https://bigfun.com.vn/',N'Học tập & Giải Trí'),
(N'BIGFUN TEEN CLUB','bigfunteen.jpg','https://bigfun.com.vn/',N'Học tập & Giải Trí'),
(N'PHOTO TIME','photo.jpg','https://www.facebook.com/phototimevn/?gidzl=uROxMqOxJKpXgZvQHY54IkwkDr9V9K1AywbcMric51YXgpDU3NKG6gloQWCDAH16fFDbKsIVlq8WJpXEJ0',N'Học tập & Giải Trí'),
(N'KIDS Zone','kidzone.jpg','NULL',N'Học tập & Giải Trí'),
(N'Power Bowl 388','bowl.jpg','https://powerbowl.vn/',N'Học tập & Giải Trí'),
(N'CGV Cinema','cgv.jpg','https://www.cgv.vn/',N'Học tập & Giải Trí'),
(N'CITIGYM','citygym.jpg','https://citigym.com.vn/',N'Học tập & Giải Trí'),
(N'RAINBOW','rainbow.jpg','https://www.rb-land.com/?fbclid=IwY2xjawF7HOFleHRuA2FlbQIxMAABHQ-NRrd_fBSzeV09C-xJt3vHfLBPrJ7FLu117iqt6gQ7dekVfRp-WWpVDA_aem_k6uN6IlEdlsgCRd46ucIKQ',N'Học tập & Giải Trí'),
(N'Dream Kids','dreamkid.jpg','https://dreamgames-net.com/vi/',N'Học tập & Giải Trí');